version: "3"

services:
  node:
    image: node:16
    user: node
    container_name: all_for_one
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
  db:
    container_name: all_for_one_db
    image: mysql:5.7.40
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
  default:
    name: all_for_one_net